# Generated by Django 4.2.4 on 2023-09-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_songs_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
